#!/usr/bin/env bash

# Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx

# Set proper permissions for the index.html file
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo chown www-data:www-data /var/www/html/index.html
sudo chmod 644 /var/www/html/index.html

# Restart nginx service
sudo service nginx restart
