#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_to_replace="server_name _;\n\trewrite ^\/redirect_me https://youtu.be/U8B2DPYewBI?si=Qq3Wae-U1WaFTNa1 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
